### ISSUE TITLE
Link to the http://inflector.cakephp.org/ on CakePHP 3.0 docs points to a 2.5.5 version

### ISSUE THREAD

**Issue by volponi** [cakephp/docs#2785]
Hello,

Inside http://book.cakephp.org/3.0/en/core-libraries/inflector.html there is a link to http://inflector.cakephp.org/, which is a 2.5.5 Inflector example.

It's better to point to a 3.x inflector online example, or remove the link.

**Comment by markstory** [comment]
I think we have to update the inflector site/app.

**Comment by ravage84** [comment]
Either that or have two different inflector pages, because if the Inflector of 2.x and 3.x lose inflection parity, it could confuse people using the tool page.

What we could do though is to update it to 3.x and put up a warning sign that it uses the Inflector of 3.x under the hood and that it *could* differ from the one in 2.x.

**Comment by dereuromark** [comment]
I just use http://sandbox3.dereuromark.de/sandbox/inflector :)

**Comment by ionas** [comment]
inflector3.cakephp.org maybe.

**Comment by ravage84** [comment]
Last update two years ago. Are we still going to do this?

The inflector site repo is publicly available:
https://github.com/cakephp/inflector.cakephp.org

Anybody interested can put up a PR.

**Comment by markstory** [comment]
Closing this as the changes need to be made in inflector.cakephp.org
