### ISSUE TITLE
save language choice in a cookie

### ISSUE THREAD

**Issue by danielzzz** [cakephp/docs#3519]
hi, it would be great if the language choice could be saved somehow. 
right now I connect from Spain and every time I have to switch back to English, which is a bit of a hassle sometimes...

thanks! best
dan

**Comment by markstory** [comment]
Wouldn't a bookmark let you save the URL you wanted to see?

**Comment by inigoflores** [comment]
I understand what @danielzzz is complaining about, as I've been experiencing the same frustration lately (also from Spain :)

I believe many of us access the Cookbook through Google, who happens to have indexed all of those empty sections in Spanish. So, every time you visit the Cookbook by following a Google search result, you have to manually change the language through the language dropdown.

Even if the Spanish version of the Cookbook was complete, I would still prefer to access it in English. Using google.co.uk instead of google.es is a workaround, but it's still a hassle.

The same would be applicable to the different CakePHP versions. E.g. I work mostly on 2.x projects, but I have recently started with the CakePHP 3. From Google, landing on the right language and version is a bit of a lottery :)

Switching versions is even more cumbersome, as the the version dropdown does not exhibit the same behavior as the language selector does with regards to deep linking (it takes you to the version homepage instead of the relevant section). 

I believe the language issue can be easily addressed with a nginx rewrite/redirect based on the cookie content.

**Comment by markstory** [comment]
The version picker is a challenge as files move between the versions and finding semantic equivalence is pretty hard.

I'd prefer to not put language toggles in nginx, as the book uses 4 different virtualhosts (1 for each version) and keeping nginx config in sync will not be fun.

**Comment by inigoflores** [comment]
A possible approach for the version picker would be to just link to the relevant section, which will work fine if there is semantic equivalence, but will fail with a 404 error if not. A custom error handler could then catch these requests, and offer a custom 404 page holding a list of relevant search results. Not sure if this makes sense. It's probably not worth the effort, as adding the version number to the google search should take you the right version.

Regarding the language toggle, I understand there are technical limitations which are beyond my understanding of how your systems work. Also, it's probably not a critical issue. Using google.co.uk does the trick.

Thanks!

**Comment by markstory** [comment]
> I understand there are technical limitations which are beyond my understanding of how your systems work.

The book is a painfully simple site made of static HTML that is generated from the source files. Integrating dynamic error pages might be a good idea though, as the current 404 experience is not very good.

**Comment by ravage84** [comment]
How do we progress on this matter? It does not seem to be easily implemented...

**Comment by markstory** [comment]
@ravage84 No, I don't think it is easily implemented and there doesn't seem to be enough interest for someone to take it on.
