### ISSUE TITLE
Documentation webpage broken by proxy firewall (Facebook issues)

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/docs#3915]
When visiting `http://cakephp.org/pages/documentation` behind a firewall that blocks `www.facebook.com` the page is missing most of it's contents.

![image](https://cloud.githubusercontent.com/assets/551022/14640096/e0567738-060d-11e6-9b01-711eff2882fb.png)

It appears that a JavaScript error in `widgets.js` causes a cascading error that prevents the rest of the page from being rendered properly.

The BOOK and API documentation sites appear to be working fine. It's just this page that is broken.

**Comment by chinpei215** [comment]
@markstory How is it afterwards? 
It seems to me that this issue is not related with Facebook. Chrome seems to apply `-webkit-mask` style unexpectedly. Disabling the sytle, the content appears.
![broken](https://cloud.githubusercontent.com/assets/7399393/14845654/971a6b90-0c9a-11e6-80bf-58575dece69d.png)

**Comment by markstory** [comment]
@chinpei215 I didn't even know there were svg masks in the CSS for the site.

**Comment by thinkingmedia** [comment]
I can reproduce this problem with Chrome 50.0.2661.86 (64-bit) on Ubuntu 16.04 while at home. So it's got nothing to do with Facebook.

**Comment by chinpei215** [comment]
@markstory Chrome also seems not support using an svg in the `-webkit-clip-path` style.
In addition to remove `-webkit-mask`, it might be better to use `polygon(0 255px,3000px 310px,100% 0,0 0)` instead of `url(clip-scnd.svg#svgClip)`. Unfortunately, since my macbook was destroyed by Heineken, I cannot confirm it on Mac anymore :cry: 
Can you check whether this change breaks Safari or not, if I open a pull request?
![broken2](https://cloud.githubusercontent.com/assets/7399393/14883524/93698eec-0d79-11e6-8065-1b557899128c.png)

**Comment by markstory** [comment]
@chinpei215 I can check safari. I checked firefox last night and everything was fine there.

**Comment by chinpei215** [comment]
@thinkingmedia I've fixed it just now. Could you please check whether this issue is solved or not?

**Comment by markstory** [comment]
Looks good to me on Chrome and Safari on OSX.

**Comment by thinkingmedia** [comment]
@chinpei215 great job, thank you. It's working now.

**Comment by chinpei215** [comment]
Thanks!
