### ISSUE TITLE
3.3+ Missing examples for Middleware such as AssetMiddleware

### ISSUE THREAD

**Issue by htstudios** [cakephp/docs#4253]
When Reading https://github.com/cakephp/cakephp/pull/9262 I realised that there are quite a bunch of cool DispatchFilters I never read/knew about.

The docs for `AssetFilter` etc. are explaining how to use it while those based on Middleware do not. It simply mentions that there is `AssetMiddleware` but there is missing an example on how to use it @ http://book.cakephp.org/3.0/en/controllers/middleware.html

**Comment by markstory** [comment]
Most of the core middleware are pretty simple, what kind of examples would you like to see?

**Comment by inoas** [comment]
@markstory 
I meant the chapters on http://book.cakephp.org/3.0/en/development/dispatch-filters.html
Especially http://book.cakephp.org/3.0/en/development/dispatch-filters.html#building-a-filter
And examples to http://book.cakephp.org/3.0/en/development/dispatch-filters.html#built-in-filters

e.g. it would be very cool if any examples and explanatory sections of the dispatchers chapter would reappear 1:1 on the middleware chapter so that you can compare the chapters to get a good feeling/foundation on how to move from Dispatch Filters to Middleware.

**Comment by markstory** [comment]
There is a section for [creating middleware](http://book.cakephp.org/3.0/en/controllers/middleware.html#creating-middleware) which is analogous to the 'building a filter' section. There is also a brief description of [the built in middleware](http://book.cakephp.org/3.0/en/controllers/middleware.html#middleware) at the beginning of the middleware chapter.

Are there parts of the 'creating middleware' section that could be clearer, more thorough?

**Comment by inoas** [comment]
The creating middleware is clear however an 1 to 1 example of this would be good

```php
        $request = $event->data['request'];
        $response = $event->data['response'];
        if (!$request->cookie('landing_page')) {
            $response->cookie([
                'name' => 'landing_page',
                'value' => $request->here(),
                'expire' => '+ 1 year',
            ]);
        }
```

Would it be as simple as this?:

```php

namespace App\Middleware;

class TrackingCookieMiddleware
{
    function __invoke($request, $response, $next)
    {
        if (!$request->cookie('landing_page')) {
            $response->cookie([
                'name' => 'landing_page',
                'value' => $request->here(),
                'expire' => '+ 1 year',
            ]);
        }

        // Calling $next() delegates control to then *next* middleware
        // In your application's queue.
        $response = $next($request, $response);

        // We could further modify the response before returning it.
        return $response;
}
```

Plus *Loading in Application.php?*

If that's the case, maybe that should be the first example, and it should directly be linked (with chapter #/anchor) from the dispatchers chapter. So that it makes it easy to transition.

* * *

The original Chapter has an souce-code-snipplet example on how to load the AssetFilter. The new chapter should have one, too?

**Comment by markstory** [comment]
I think I've made the suggested improvements. I didn't add a usage example to the AssetMiddleware bullet point, as the *next* section covers how to add middleware to an application.
