### ISSUE TITLE
Create Russian skeleton

### ISSUE THREAD

**Issue by Fector** [cakephp/docs#4509]
I am wiling translate docs to Russian language.

**Comment by ravage84** [comment]
Hi @Fector, glad to hear that.
Are you a single person or do you have people around you supporting your efforts?

I ask because in the past we had a Russian translation of the CakePHP 2.x Cookbook.
We deleted it after it got abandoned and outdated in the end.

Also would you want to translate the 2.x or 3.x version of the book?

**Comment by Fector** [comment]
Hi @ravage84. There are two of us. We wants to translate 3.x version.

**Comment by cake17** [comment]
Hi @Fector, thanks for your help, I can create a skeleton for the russian language.

Before that, can we be sure that you'll  translate at least the files described [here](http://book.cakephp.org/3.0/en/contributing/documentation.html#new-translation-language) ? Sorry to ask again but having just partials documentation is not helping users and as @ravage84 says, in the past there were lots of outdated translations.

Please read the [contribution documentation](http://book.cakephp.org/3.0/en/contributing/documentation.html) to follow the guidelines and if you need any help, let us know.

**Comment by Leo240** [comment]
I'm also  interested in this @ravage84 @cake17

**Comment by cake17** [comment]
@Fector @Leo240 the ru skeleton is built with PR #4603, I close this issue ! Have a good translation ! 😄
