### ISSUE TITLE
Migrations - change or up

### ISSUE THREAD

**Issue by toby1kenobi** [cakephp/docs#4655]
[Migrations doc](https://book.cakephp.org/3.0/en/migrations.html) uses both change() and up() in examples, I don't know if this is intentional but it would surely be worth mentioning the difference (or maybe just sticking to change())?

**Comment by HavokInspiration** [comment]
Both are useful in their ways.

A migration has 3 "operations" methods : `up()`, `down()` and `change()` :

- `up()` is used when you run `bin/cake migrations migrate`
- `down()` is used when you `bin/cake migrations rollback`
- `change()` is used in both cases. If you use it in a migrate context, it will apply the content of the method ; if you use it in a rollback context, it will apply the opposite of the content of the method. Basically with `change` you only need to write the `up` logic.

On a side note, if you have the three methods in you migrations, phinx will ignore `up` and `down` and only use `change`.

The `change()` method however can only reverse the following methods :

- createTable
- renameTable
- addColumn
- renameColumn
- addIndex
- addForeignKey

Instructions in `change()` with `insert()`, `drop()` or raw queries made can not be reversed. If you need those type of cases in your `up` logic, you should use the `up()` and `down()` methods.

So it mainly depends on what you need to do with your migrations. In most cases, I found that using `change()` should be enough. But when dealing with foreign keys, `up()` and `down()` are better in my opinions because it allows to remove the FK before deleting the table for instance.

I can add a note in the docs using this answer if that feels clear enough for you.
If you have more questions, please ask, that will help me to write something useful.

**Comment by toby1kenobi** [comment]
Thanks for getting back to me. It seems to me that it would at least be useful to briefly describe why someone would use change() or up()/down().

**Comment by saeideng** [comment]
docs described here https://book.cakephp.org/3.0/en/phinx/migrations.html
