### ISSUE TITLE
Add Middleware Onion to the docs

### ISSUE THREAD

**Issue by inoas** [cakephp/docs#5087]
@markstory  Could we have 2 graphics ... those at https://www.youtube.com/watch?v=DtH__Iz9Mjs at 19m32s and that at 20m00s ... maybe as an anim gif or 2 graphics... maybe one more injecting an onion ring.

That should help people understand better?

p.s.: I have been creating my own NotFoundMiddleware and found it amazing to stop the framework from loading early in a clean way - thanks for doing this - much better than DispatchFilters.

**Comment by markstory** [comment]
Where would you see that fitting in? Would it make sense as part of the intro to [middleware](https://book.cakephp.org/3.0/en/controllers/middleware.html)?

**Comment by ravage84** [comment]
@markstory  alternatively, somewhere around [here](https://book.cakephp.org/3.0/en/intro.html#cakephp-request-cycle). Or link from there to [middleware](https://book.cakephp.org/3.0/en/controllers/middleware.html) (which is already the case, btw), where we place that image.

I would prefer an image, instead of a gif. Simply, because it can be better printed/exported to PDF.

**Comment by inoas** [comment]
@ravage84 good point regarding printing

I also thought about request-response circle... maybe there could be one image of the onion there and in the chapter about middleware we can use the same image and 2 more for explaining how to stop requests early and/or how to modify request/response while moving into/out of the onion layers.

**Comment by markstory** [comment]
Pull request open now.
