### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [cakephp/docs#5392]
License is generally regarded as a must for Open Source Projects. So, I think it is a good idea to add License to this project. I would like to start a discussion on that matter.

**Comment by markstory** [comment]
It would likely be MIT like all the other CakePHP projects. cc @phpnut

**Comment by ArmenGabrielyan16** [comment]
I agree that's a good point. It would be nice to stay consistent with other CakePHP projects.

**Comment by inoas** [comment]
No legally speaking it is probably hard to add a license now, but I assume CC0 or MIT will work.
https://choosealicense.com/non-software/
https://choosealicense.com/licenses/cc0-1.0/

**Comment by ArmenGabrielyan16** [comment]
@inoas Could you please elaborate why it is legally hard to add a license now?

**Comment by inoas** [comment]
> @inoas Could you please elaborate why it is legally hard to add a license now?

Under what license did contributors submit their PRs so far? Probably none? So what license are things about

Don't get me wrong, I don't "like" licenses but we are living in a world where you have to / should add one. And GNU FDL or CC0 are perfect for the job, MIT probably also works.

I am no legal expert but this looks like re-licensing *to me*. I am not worried *personally* but I am not sure if it is legally okay (and adding a license is something you do to F(L)OSS documentation only because of legal issues IMHO).

**Comment by dereuromark** [comment]
The license is already in there since the beginning: https://github.com/cakephp/docs/blame/3.0/README.md#L4
MIT clearly stated
So please don't overcomplicate things.

**Comment by inoas** [comment]
I don't see it. Please follow the CoC and do not try to shut up people by disregarding issues just because you don't see or share the point.

As I said, I do not have any personal issue with adding a F(L)OSS license to cakephp/docs at all, I am just saying that if you do this then there can be liabilities and for sure not by me. And regarding licenses - changing the one of cakephp/app didn't happen yet (which is actually a real issue) and we are waiting for 2 years.

So I my point of view: Either ignore possible legal issues (in your words: "don't overcomplicate things") and just change the license to MIT (maybe you want to merge that, then you are liable in case there is legal trouble), or phpnut really has to chime in and maybe get an answer from his lawyer.

**Comment by ArmenGabrielyan16** [comment]
So are we going to add a License?

**Comment by dereuromark** [comment]
Feel free to open a PR.

> I don't see the file. Do you?

@inoas Please stay civil. You are a bit too aggressive in your engagement in issues sometimes that do not necessarily need that much of your attention.
The file does not have to be present for the very clear sign of MIT present to make this an MIT issue. So adding the file itself is - from a legal perspective - just more clarification.
One cannot argue anything else, and no on is changing anything or disregarding anything.

**Comment by dereuromark** [comment]
Also the link should be changed of course so the file linked can be found again :)
That is sure sth that can also be  PR (rather than many words of aggressive challenge of the current license).

**Comment by inoas** [comment]
Again @dereuromark why in OS projects do you try to shut out people? "that do not necessarily need that much of your attention" Please be inclusive and follow the CoC.

Then if the file once existed it is troubling, but I cannot find the file in the repo. Can you show me where it exists/existed? Can you legally back up your claim that just "naming a license" without actually supplying the license in the headers or at least the root of the repo is legally sound? Are you a legal expert? I am not but it seems you are.

**Comment by dereuromark** [comment]
Can you please just let the people responsible for the repo be responsible for the repo?
I am sure you do have other things to wry about than what we need to do legally (especially since you are not an expert in that field trying to aggressivly put doubts where they are misplaced).

You voiced your concern, this is noted and will be taken into consideration. Everything else you did afterwards was inappropriate and personal (trying to argue with CoC as well).

So please let this go and again, keep it civil.

**Comment by dereuromark** [comment]
PR now open.
