### ISSUE TITLE
Unsatisfactory results for keyword "Command"

### ISSUE THREAD

**Issue by ADmad** [cakephp/docs#5801]
Searching for keyword "command" on the manual doesn't list the page https://book.cakephp.org/3.0/en/console-and-shells/commands.html at all. I would expect it to be the first one listed.

I would also expect this page https://book.cakephp.org/3.0/en/console-and-shells.html  to be somewhere near the top of the results list while it's listed 8th currently.

**Comment by othercorey** [comment]
I noticed this was working now.  Perhaps it's the change to use `3-0` instead of `3-next` search index?

https://github.com/cakephp/docs/commit/23b42113640653045debe7d0f44856ec074dcd73

I just happened to notice the weird 3-next search index working on a separate change and wondered if it was right.
