### ISSUE TITLE
Missing event stop propagation docs

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#6242]
I was following https://book.cakephp.org/3.0/en/orm/behaviors.html#defining-event-listeners
but not for behaviors, but for a table

Just doing documented (for behavior beforeSave):
```php
    $entity->setError('name', 'Invalid name.');
    $event->stopPropagation();
    return;
```
didnt work

I had to manually find out that one needs to add
```php
    $entity->setError('name', 'Invalid name.');
    $event->stopPropagation();
    $event->setResult(false);
    return;
```
inside my Table's beforeSave().

Is this specific to tables and just documented yet?

**Comment by ADmad** [comment]
Looking at this code just stopping the event should be enough to stop the save.

https://github.com/cakephp/cakephp/blob/9c8f6728a2f9cfbf8f77332e55f18fc9b93167ec/src/Event/EventManager.php#L329-L334

Only thing is if you don't return false from the callback or explicitly set the even result `Table::save()` will return `null` instead of the documented `false` or entity.
