### ISSUE TITLE
Russian docs remove

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/docs#7040]
Russian docs for 3.x/4.x are lot outdated and awfully translated, many pages are just empty. 
Its almost impossible to read and use it, but google always shows it first in search results for Russia and Ukraine.

Should not we remove that and setup redirects to English?

**Comment by ndm2** [comment]
The same is more or less true for the Portuguese, Chinese, Spanish and Turkish docs, is there really a point in having all these when there's only bits of them translated, many of it machine translated?

If it were up to me, I'd drop all translations, so that the community could focus all their effort on improving one single language. The translations always get out of sync, and without dedicated teams that keep them up to date, this will never change and only worsen over time 😟

**Comment by othercorey** [comment]
I would like to setup an "intro" page or small section that we encourage to be translated. Unfortunately, it's difficult to do with the current framework because the other pages don't link back to english.
